const STORES=[{id:"walmart",label:"Walmart"},{id:"target",label:"Target"},{id:"whole_foods",label:"Whole Foods"},{id:"sams",label:"Sam’s"}];
const AISLES=["Drinks","Fruit","Dairy","Meat","Bakery","Snacks","Pantry","Frozen","Health","Household"];
const PRODUCTS=[
{id:"diet-coke-minis",aisle:"Drinks",name:"Diet Coke mini cans",brand:"Coca-Cola",packHint:"10pk",buy:2,offers:{walmart:{price:6.37,pack:"10pk 7.5",base:75,uom:"fl oz",kind:"shelf"},target:{price:7.49,pack:"10pk 7.5",base:75,uom:"fl oz",kind:"shelf"},whole_foods:{notSold:true},sams:{price:19.78,pack:"30pk",base:225,uom:"fl oz",kind:"shelf"}}},
{id:"fiji-24",aisle:"Drinks",name:"FIJI water",brand:"FIJI",packHint:"24pk",buy:4,offers:{walmart:{price:25.89,pack:"24pk",base:405.6,uom:"fl oz",kind:"shelf"},target:{price:5.99,pack:"6pk",base:101.4,uom:"fl oz",kind:"shelf"},whole_foods:{price:5.99,pack:"6pk",base:101.4,uom:"fl oz",kind:"shelf"},sams:{price:21.98,pack:"24pk",base:405.6,uom:"fl oz",kind:"shelf"}}},
{id:"hint-water",aisle:"Drinks",name:"Hint water",brand:"Hint",packHint:"12pk",buy:3,offers:{walmart:{price:13.46,pack:"12pk",base:192,uom:"fl oz",kind:"shelf"},target:{price:14.99,pack:"12pk",base:192,uom:"fl oz",kind:"shelf"},whole_foods:{price:12.99,pack:"12pk",base:192,uom:"fl oz",kind:"shelf"},sams:{price:11.78,pack:"12pk",base:192,uom:"fl oz",kind:"shelf"}}},
{id:"fairlife-2pct",aisle:"Dairy",name:"Fairlife lactose-free 2%",brand:"Fairlife",packHint:"52 fl oz",buy:2,offers:{walmart:{price:4.78,pack:"52",base:52,uom:"fl oz",kind:"shelf"},target:{price:4.79,pack:"52",base:52,uom:"fl oz",kind:"shelf"},whole_foods:{notSold:true},sams:{notSold:true}}},
{id:"kerrygold-oo",aisle:"Dairy",name:"Kerrygold butter + olive oil",brand:"Kerrygold",packHint:"7.5 oz",buy:3,offers:{walmart:{price:4.96,pack:"7.5",base:7.5,uom:"oz",kind:"shelf"},target:{price:5.29,pack:"7.5",base:7.5,uom:"oz",kind:"shelf"},whole_foods:{price:5.99,pack:"7.5",base:7.5,uom:"oz",kind:"shelf"},sams:{price:10.34,pack:"17.6",base:17.6,uom:"oz",kind:"shelf"}}},
{id:"avocado",aisle:"Fruit",name:"Hass avocado",brand:"",packHint:"each",buy:5,offers:{walmart:{price:0.65,pack:"each",base:1,uom:"ea",kind:"shelf"},target:{price:1.19,pack:"each",base:1,uom:"ea",kind:"shelf"},whole_foods:{price:1.79,pack:"large",base:1,uom:"ea",kind:"shelf"},sams:{price:4.23,pack:"5ct",base:5,uom:"ea",kind:"shelf"}}},
{id:"heinz",aisle:"Pantry",name:"Heinz Simply ketchup",brand:"Heinz",packHint:"31 oz",buy:4,offers:{walmart:{price:5.58,pack:"31oz",base:31,uom:"oz",kind:"shelf"},target:{price:6.99,pack:"31oz",base:31,uom:"oz",kind:"shelf"},whole_foods:{price:5.99,pack:"19oz",base:19,uom:"oz",kind:"shelf"},sams:{price:9.98,pack:"2x44",base:88,uom:"oz",kind:"shelf"}}},
{id:"doritos",aisle:"Snacks",name:"Doritos Cool Ranch",brand:"Doritos",packHint:"9.25 oz",buy:2,offers:{walmart:{price:4.24,pack:"9.25",base:9.25,uom:"oz",kind:"typical"},target:{price:4.59,pack:"9.25",base:9.25,uom:"oz",kind:"shelf"},whole_foods:{notSold:true},sams:{notSold:true}}},
{id:"olly-pro",aisle:"Health",name:"OLLY probiotic",brand:"OLLY",packHint:"70 ct",buy:4,offers:{walmart:{price:16.97,pack:"70",base:70,uom:"ea",kind:"typical"},target:{price:18.89,pack:"70",base:70,uom:"ea",kind:"shelf"},whole_foods:{price:17.79,pack:"50",base:50,uom:"ea",kind:"shelf"},sams:{price:19.88,pack:"70",base:70,uom:"ea",kind:"shelf"}}},
{id:"olly-mens",aisle:"Health",name:"OLLY men multi",brand:"OLLY",packHint:"200 ct",buy:2,offers:{walmart:{price:17.98,pack:"90",base:90,uom:"ea",kind:"typical"},target:{price:17.99,pack:"130",base:130,uom:"ea",kind:"shelf"},whole_foods:{price:16.99,pack:"90",base:90,uom:"ea",kind:"typical"},sams:{price:17.98,pack:"200",base:200,uom:"ea",kind:"shelf"}}},
{id:"natures-own-buns",aisle:"Bakery",name:"Nature's Own brioche hot dog buns",brand:"Nature's Own",packHint:"8 ct",buy:2,offers:{walmart:{price:3.44,pack:"8ct",base:8,uom:"ea",kind:"shelf"},target:{price:3.99,pack:"8ct",base:8,uom:"ea",kind:"typical"},whole_foods:{notSold:true},sams:{notSold:true}}},
{id:"puffs-plus",aisle:"Household",name:"Puffs Plus 12 cubes",brand:"Puffs",packHint:"12x72",buy:2,offers:{walmart:{price:25,pack:"12",base:864,uom:"ea",kind:"typical"},target:{price:11.19,pack:"6",base:432,uom:"ea",kind:"shelf"},whole_foods:{notSold:true},sams:{price:18.34,pack:"12",base:864,uom:"ea",kind:"shelf"}}}
];
const extra=JSON.parse(localStorage.getItem("spw-extra")||"[]");
let catalog=PRODUCTS.concat(extra);
let cart=JSON.parse(localStorage.getItem("spw-cart")||"{}");
let filter="All",sortAlpha=false;
function unitOf(o){return (!o||o.notSold)?null:o.price/o.base}
function unitLabel(o){const u=unitOf(o);if(u==null)return null;if(o.uom==="ea")return "$"+u.toFixed(2)+"/ea";if(o.uom==="lb")return "$"+u.toFixed(2)+"/lb";return "$"+u.toFixed(2)+"/"+o.uom}
function bestStore(p){let b=null,bu=Infinity;for(const s of STORES){const u=unitOf(p.offers[s.id]);if(u!=null&&u<bu){bu=u;b=s.id}}return b}
function save(){localStorage.setItem("spw-cart",JSON.stringify(cart));localStorage.setItem("spw-extra",JSON.stringify(extra))}
const chipsEl=document.getElementById("chips");
function renderChips(){const labels=["All","Needs a price","A–Z",...AISLES];chipsEl.innerHTML=labels.map(l=>{const on=(l==="A–Z"&&sortAlpha)||(l!=="A–Z"&&filter===l);return '<button class="chip '+(on?"on":"")+'" data-c="'+l+'">'+l+'</button>'}).join("")}
chipsEl.onclick=e=>{const c=e.target.dataset.c;if(!c)return;if(c==="A–Z")sortAlpha=!sortAlpha;else filter=c;render()};
document.getElementById("q").oninput=render;
document.getElementById("addBtn").onclick=()=>{const name=document.getElementById("newName").value.trim();if(!name)return;extra.push({id:"custom-"+Date.now(),aisle:"Pantry",name,brand:"",packHint:"",buy:0,offers:{walmart:null,target:null,whole_foods:null,sams:null}});document.getElementById("newName").value="";save();catalog=PRODUCTS.concat(extra);render()};
function needsPrice(p){return STORES.some(s=>!p.offers[s.id])}
function renderList(){const q=document.getElementById("q").value.trim().toLowerCase();let items=catalog.filter(p=>{if(q&&!(p.name+" "+p.brand).toLowerCase().includes(q))return false;if(filter==="Needs a price")return needsPrice(p);if(filter!=="All"&&p.aisle!==filter)return false;return true});items.sort((a,b)=>{if(sortAlpha||filter==="A–Z")return a.name.localeCompare(b.name);const ai=AISLES.indexOf(a.aisle),bi=AISLES.indexOf(b.aisle);if(ai!==bi)return ai-bi;return b.buy-a.buy||a.name.localeCompare(b.name)});const root=document.getElementById("list");if(!items.length){root.innerHTML='<div class="empty">Nothing in this view.</div>';return}let html="",last="";for(const p of items){if(!sortAlpha&&filter!=="A–Z"&&p.aisle!==last){html+='<div class="aisle">'+p.aisle+'</div>';last=p.aisle}const best=bestStore(p);const buttons=STORES.map(s=>{const o=p.offers[s.id],picked=cart[p.id]===s.id;if(!o)return '<button class="store miss" data-id="'+p.id+'" data-s="'+s.id+'"><span class="s">'+s.label+'</span><span class="u">Not yet</span><span class="p">tap to add price</span></button>';if(o.notSold)return '<button class="store miss" disabled><span class="s">'+s.label+'</span><span class="u">Not sold</span></button>';return '<button class="store'+(best===s.id?' best':'')+(picked?' picked':'')+'" data-id="'+p.id+'" data-s="'+s.id+'"><span class="s">'+s.label+'</span><span class="u">'+unitLabel(o)+'</span><span class="p">$'+o.price.toFixed(2)+' \xb7 '+o.pack+'</span></button>'}).join('');html+='<article class="card"><div class="name">'+(p.brand?p.brand+' \xb7 ':'')+p.name+'</div><div class="meta">'+(p.packHint||'')+'</div><div class="stores">'+buttons+'</div></article>'}root.innerHTML=html}
document.getElementById("list").onclick=e=>{const btn=e.target.closest("button.store");if(!btn||btn.disabled)return;const id=btn.dataset.id,s=btn.dataset.s,p=catalog.find(x=>x.id===id);if(!p.offers[s]){promptPrice(p,s);return}if(cart[id]===s)delete cart[id];else cart[id]=s;save();render()};
function promptPrice(p,s){const dlg=document.getElementById("dlg");dlg.innerHTML='<form method="dialog"><b>Add price</b><p>'+p.name+'</p><input name="price" type="number" step="0.01" placeholder="Pack price" required style="width:100%;padding:10px;margin:6px 0"/><input name="pack" placeholder="Pack" style="width:100%;padding:10px;margin:6px 0"/><input name="base" type="number" step="0.01" placeholder="Units in pack" style="width:100%;padding:10px;margin:6px 0"/><select name="uom" style="width:100%;padding:10px;margin:6px 0"><option value="oz">oz</option><option value="fl oz">fl oz</option><option value="ea">each</option><option value="lb">lb</option></select><button value="cancel">Cancel</button><button value="miss">Not sold</button><button value="ok">Save</button></form>';dlg.showModal();dlg.querySelector("form").addEventListener("close",()=>{const f=dlg.querySelector("form"),v=dlg.returnValue;if(v==="miss"){p.offers[s]={notSold:true};save();render()}if(v==="ok"){const price=parseFloat(f.price.value),base=parseFloat(f.base.value||"1");if(!price)return;p.offers[s]={price,pack:f.pack.value||"pack",base,uom:f.uom.value,kind:"shelf"};save();render()}},{once:true})}
function renderCart(){const ids=Object.keys(cart);const by={walmart:0,target:0,whole_foods:0,sams:0},n={walmart:0,target:0,whole_foods:0,sams:0};for(const id of ids){const p=catalog.find(x=>x.id===id);const o=p&&p.offers[cart[id]];if(o&&!o.notSold){by[cart[id]]+=o.price;n[cart[id]]++}}const total=Object.values(by).reduce((a,b)=>a+b,0);const bags=STORES.filter(s=>n[s.id]).map(s=>s.label+' '+n[s.id]+' $'+by[s.id].toFixed(2)).join(' \xb7 ');document.getElementById("cart").innerHTML='<div class="row"><div><b>Cart '+ids.length+' \xb7 $'+total.toFixed(2)+'</b><div class="bags">'+(bags||"Tap a store tile")+'</div></div><button onclick="cart={};save();render();" style="background:#fff;color:#1c1914;border:0;border-radius:10px;padding:8px 10px">Clear</button></div>'}
function render(){renderChips();renderList();renderCart()}render();
