const STORES=[{id:"walmart",label:"Walmart"},{id:"target",label:"Target"},{id:"whole_foods",label:"Whole Foods"},{id:"sams",label:"Sam’s"}];
const AISLES=["Pending","Drinks","Fruit","Dairy","Meat","Bakery","Snacks","Pantry","Frozen","Health","Household"];
const LS_CART="spw-cart",LS_PENDING="spw-pending",LS_OVERRIDES="spw-overrides";
let catalog=[]; let priceBook={asOf:"",offers:{}};
let cart=load(LS_CART,{}); let pending=load(LS_PENDING,[]); let overrides=load(LS_OVERRIDES,{});
let filter="All", sortAlpha=false;
function formatAsOf(s){if(!s)return"unknown";const m=/^(\d{4})-(\d{2})-(\d{2})/.exec(String(s).trim());if(m)return m[2]+"/"+m[3]+"/"+m[1];return String(s);}

function load(key,fallback){try{return JSON.parse(localStorage.getItem(key)||"null")??fallback;}catch(e){return fallback;}}
function save(key,val){localStorage.setItem(key,JSON.stringify(val));}
function offerOf(id,storeId){const ovr=overrides[id]&&overrides[id][storeId]; if(ovr)return ovr; const book=priceBook.offers[id]||{}; return book[storeId]??null;}
function unitOf(o){if(!o||o.notSold||!o.base)return null; return o.price/o.base;}
function unitLabel(o){const u=unitOf(o); if(u==null)return null; if(o.uom==="ea")return "$"+u.toFixed(2)+"/ea"; if(o.uom==="lb")return "$"+u.toFixed(2)+"/lb"; return "$"+u.toFixed(2)+"/"+o.uom;}
function bestStore(id){let best=null,bestU=Infinity; for(const s of STORES){const u=unitOf(offerOf(id,s.id)); if(u!=null&&u<bestU){bestU=u;best=s.id;}} return best;}
function slug(name){return name.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"")||("item-"+Date.now());}
function allProducts(){return catalog.concat(pending.map(function(p){return Object.assign({pending:true},p);}));}
function patchPayload(){const addToCatalog=pending.map(function(p){return {id:p.id,aisle:p.aisle==="Pending"?"Pantry":p.aisle,name:p.name,brand:p.brand||"",packHint:p.packHint||"",buyCount:p.buy||p.buyCount||0};}); const merge={}; pending.forEach(function(p){const row={}; STORES.forEach(function(s){const o=offerOf(p.id,s.id); if(o)row[s.id]=o;}); merge[p.id]=row;}); Object.keys(overrides).forEach(function(id){if(!merge[id])merge[id]=overrides[id]; else Object.assign(merge[id],overrides[id]);}); return {addToCatalog:addToCatalog,mergeIntoPrices:merge};}
async function boot(){try{const cRes=await fetch("catalog.json?v=5",{cache:"no-store"}); const pRes=await fetch("prices.json?v=5",{cache:"no-store"}); if(!cRes.ok||!pRes.ok)throw new Error("Could not load catalog.json / prices.json"); const c=await cRes.json(); const p=await pRes.json(); catalog=Array.isArray(c)?c:(c.products||[]); catalog=catalog.map(function(row){return Object.assign({},row,{buy:row.buy!=null?row.buy:(row.buyCount||0)});}); priceBook={asOf:p.asOf||"",offers:p.offers||p.items||{}}; document.getElementById("asOf").textContent=formatAsOf(priceBook.asOf); render();}catch(err){document.getElementById("list").innerHTML='<div class="err">Open this app from the hosted link so catalog.json can load. '+err.message+"</div>";}}
function renderChips(){const labels=["All","Needs a price","A–Z"].concat(AISLES); document.getElementById("chips").innerHTML=labels.map(function(l){const on=(l==="A–Z"&&sortAlpha)||(l!=="A–Z"&&filter===l); return '<button class="chip '+(on?"on":"")+'" data-c="'+l+'">'+l+"</button>";}).join("");}
function needsPrice(p){return STORES.some(function(s){return !offerOf(p.id,s.id);});}
function renderList(){const q=document.getElementById("q").value.trim().toLowerCase(); let items=allProducts().filter(function(p){if(q&&!(p.name+" "+(p.brand||"")).toLowerCase().includes(q))return false; if(filter==="Needs a price")return needsPrice(p); if(filter!=="All"&&p.aisle!==filter)return false; return true;}); items.sort(function(a,b){if(sortAlpha||filter==="A–Z")return a.name.localeCompare(b.name); const ai=AISLES.indexOf(a.aisle),bi=AISLES.indexOf(b.aisle); if(ai!==bi)return ai-bi; return (b.buy||0)-(a.buy||0)||a.name.localeCompare(b.name);}); const root=document.getElementById("list"); if(!items.length){root.innerHTML='<div class="empty">Nothing in this view.</div>'; return;} let html="",last=""; items.forEach(function(p){if(!sortAlpha&&filter!=="A–Z"&&p.aisle!==last){html+='<div class="aisle">'+p.aisle+"</div>"; last=p.aisle;} const best=bestStore(p.id); const buttons=STORES.map(function(s){const o=offerOf(p.id,s.id); const picked=cart[p.id]===s.id; if(!o)return '<button class="store miss" data-id="'+p.id+'" data-s="'+s.id+'"><span class="s">'+s.label+'</span><span class="u">Not yet</span><span class="p">tap to add price</span></button>'; if(o.notSold)return '<button class="store miss" disabled><span class="s">'+s.label+'</span><span class="u">Not sold</span><span class="p">does not carry it</span></button>'; const kind=o.kind==="override"?" · typed":(o.kind==="last_paid"?" · paid":(o.kind==="typical"?" · typ":" · shelf")); return '<button class="store'+(best===s.id?" best":"")+(picked?" picked":"")+'" data-id="'+p.id+'" data-s="'+s.id+'"><span class="s">'+s.label+kind+'</span><span class="u">'+unitLabel(o)+'</span><span class="p">$'+Number(o.price).toFixed(2)+' · '+o.pack+'</span></button>';}).join(""); const cap=best?("Lowest per unit at "+STORES.find(function(s){return s.id===best;}).label):"No current price yet"; const pendingBit=p.pending?'<div class="patch"><button class="btn ghost" data-act="copy">Copy JSON</button><button class="btn ghost" data-act="dl">Download patch</button></div>':""; html+='<article class="card"><div class="name">'+(p.brand?p.brand+" · ":"")+p.name+'</div><div class="meta">'+(p.packHint||"")+' · bought '+(p.buy||0)+'×'+(p.pending?" · pending commit":"")+'</div><div class="stores">'+buttons+'</div><div class="cap">'+cap+'</div>'+pendingBit+'</article>';}); if(pending.length){html+='<article class="card"><div class="name">Pending patch ('+pending.length+' new)</div><div class="meta">Copy or download so this can be committed to catalog.json and prices.json.</div><div class="patch"><button class="btn" data-act="copy-all">Copy all pending JSON</button><button class="btn ghost" data-act="dl-all">Download patch</button></div></article>';} root.innerHTML=html;}
function renderCart(){const ids=Object.keys(cart); const by={walmart:0,target:0,whole_foods:0,sams:0}; const n={walmart:0,target:0,whole_foods:0,sams:0}; ids.forEach(function(id){const o=offerOf(id,cart[id]); if(o&&!o.notSold){by[cart[id]]+=Number(o.price); n[cart[id]]++;}}); const total=Object.keys(by).reduce(function(a,k){return a+by[k];},0); const bags=STORES.filter(function(s){return n[s.id];}).map(function(s){return s.label+' '+n[s.id]+' · $'+by[s.id].toFixed(2);}).join('  ·  '); document.getElementById("cart").innerHTML='<div class="row"><div><b>Cart '+ids.length+' · $'+total.toFixed(2)+'</b><div class="bags">'+(bags||"Tap a store tile to pick where to buy it")+'</div></div><button class="btn" style="background:#fff;color:#1c1914" id="clearCart">Clear</button></div>';}
function render(){renderChips();renderList();renderCart();}
function promptPrice(id,storeId){const p=allProducts().find(function(x){return x.id===id;}); const dlg=document.getElementById("dlg"); dlg.innerHTML='<form method="dialog"><b>Add '+STORES.find(function(x){return x.id===storeId;}).label+' price</b><p style="color:#6b6458;font-size:13px">'+(p?p.name:id)+'</p><input name="price" type="number" step="0.01" inputmode="decimal" placeholder="Pack price $" required /><input name="pack" placeholder="Pack (31 oz, 10pk)" /><input name="base" type="number" step="0.01" inputmode="decimal" placeholder="Units in pack" /><select name="uom"><option value="oz">oz</option><option value="fl oz">fl oz</option><option value="ea">each</option><option value="lb">lb</option></select><div style="display:flex;gap:8px;margin-top:8px;flex-wrap:wrap"><button value="cancel" class="btn ghost">Cancel</button><button value="miss" class="btn ghost" style="margin-left:auto">Not sold there</button><button value="ok" class="btn">Save</button></div></form>'; dlg.showModal(); dlg.querySelector("form").addEventListener("close",function(){const f=dlg.querySelector("form"); const v=dlg.returnValue; if(!overrides[id])overrides[id]={}; if(v==="miss"){overrides[id][storeId]={notSold:true,kind:"override"}; save(LS_OVERRIDES,overrides); render();} if(v==="ok"){const price=parseFloat(f.price.value); const base=parseFloat(f.base.value||"1"); if(!price)return; overrides[id][storeId]={price:price,pack:f.pack.value||"pack",base:base,uom:f.uom.value,kind:"override"}; save(LS_OVERRIDES,overrides); render();}},{once:true});}
function copyText(text){if(navigator.clipboard&&navigator.clipboard.writeText)return navigator.clipboard.writeText(text); const ta=document.createElement("textarea"); ta.value=text; document.body.appendChild(ta); ta.select(); document.execCommand("copy"); ta.remove();}
function downloadPatch(obj,name){const blob=new Blob([JSON.stringify(obj,null,2)],{type:"application/json"}); const a=document.createElement("a"); a.href=URL.createObjectURL(blob); a.download=name; a.click(); URL.revokeObjectURL(a.href);}
document.getElementById("chips").onclick=function(e){const c=e.target.dataset.c; if(!c)return; if(c==="A–Z")sortAlpha=!sortAlpha; else filter=c; render();};
document.getElementById("q").oninput=render;
document.getElementById("addBtn").onclick=function(){const name=document.getElementById("newName").value.trim(); if(!name)return; const id=slug(name); if(allProducts().some(function(p){return p.id===id||p.name.toLowerCase()===name.toLowerCase();})){document.getElementById("newName").value=""; document.getElementById("q").value=name; render(); return;} pending.push({id:id,aisle:"Pending",name:name,brand:"",packHint:"",buy:0}); save(LS_PENDING,pending); document.getElementById("newName").value=""; filter="Pending"; render();};
document.getElementById("list").onclick=function(e){const act=e.target.closest("[data-act]"); if(act){const kind=act.dataset.act; const patch=patchPayload(); if(kind==="copy"||kind==="copy-all"){copyText(JSON.stringify(patch,null,2)); act.textContent="Copied"; setTimeout(function(){act.textContent=kind==="copy"?"Copy JSON":"Copy all pending JSON";},1200);} if(kind==="dl"||kind==="dl-all")downloadPatch(patch,"sabrina-price-watch-patch.json"); return;} const btn=e.target.closest("button.store"); if(!btn||btn.disabled)return; const id=btn.dataset.id,s=btn.dataset.s; if(!offerOf(id,s)){promptPrice(id,s); return;} if(cart[id]===s)delete cart[id]; else cart[id]=s; save(LS_CART,cart); render();};
document.getElementById("cart").onclick=function(e){if(e.target.id==="clearCart"){cart={}; save(LS_CART,cart); render();}};
boot();
